### ISSUE TITLE
Code reiview

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/viewport#1]
This module port looks great, thanks @larsdesigns!!  I have noted a few super minor things below, the only one that's critical is adding the license file :)

* LICENSE.txt file is missing.

in `.install` file:

* hook_uninstall() shouldn't be necessary. If a module implements hook_config_info() the config files listed there should be deleted when the module is uninstalled.
* viewport_install() can be removed since it doesn't do anything anymore either.

in `.module` file:

* there's a blank line after `<?php` that can be removed
* viewport_autoload_info() doesn't appear to be doing anything and can be removed. 
* Nice job with the help page! This text should probably be also be placed in a wiki page so that people other than the maintainers can updated it as needed.

in `.admin.inc` file:

* there's a blank line after `<?php` that can be removed

Ohter:

* the `.test` and `.tests.info` files should be moved out of the way into a `/tests/` directory.

**Comment by larsdesigns** [comment]
1. Added the LICENSE.txt file. 
2. Completed the file edits as suggested and made individualized commits.
3. Created the wiki page with help text.

**Comment by larsdesigns** [comment]
@jenlampton, If it looks okay, I will make a release.

**Comment by jenlampton** [comment]
Yes, go ahead. The version number should be 1.x-1.4.0 (to match the Drupal version number)

**Comment by larsdesigns** [comment]
I made the release at https://github.com/backdrop-contrib/viewport/releases/tag/1.x-1.4.0. Let me know if it looks okay.

**Comment by larsdesigns** [comment]
@jenlampton, The release is a little over a month old. Is it okay to close this issue?

**Comment by jenlampton** [comment]
yes :)
